name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3     
    - name: Login to GitHub Container Registry
    
      run: |
        echo password=${{ secrets.TOKEN }} 
        docker login ghcr.io --username mohamad0880218 --password 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 



         
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/mohamad0880218/python:latest .
        docker push ghcr.io/mohamad0880218/python:latest
