name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.TOKEN }} | docker login --username your_username --password-stdin registry.example.com



         
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/mohamad0880218/python:latest .
        docker push ghcr.io/mohamad0880218/python:latest
