name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest


    steps:
     - uses: actions/checkout@v3     
     - name: Pulling images from package
       run: docker run -d -p 7000:5000 ghcr.io/mohamad0880218/python:latest
     # run: |
      #  echo pass=${{ secrets.TOKEN }}
     #   docker login ghcr.io --username mohamad0880218 --password pass

         
    #- name: Build Docker image
      #run: |
        #docker build -t ghcr.io/mohamad0880218/python:latest .
        #docker push ghcr.io/mohamad0880218/python:latest
